import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AppStoreLink, IntroductionVisit, SampleLink, UsageControl } from "../../pocket/GrowthControls";
import styles from "../page.module.css";
import "../../pocket/pocket-growth.css";

const guides = {
  indices: { title: "Challenge your index setup", headline: "Before you act on the breakout.", intro: "Bring your index chart into Pocket Bullseye. Inspect visible levels, compare the bullish and bearish cases, and identify what would challenge your idea.", question: "Is that resistance really cleared—or is price still testing it?", steps: [["Keep the instrument visible", "Include the broker's full instrument name, timeframe, candles and price scale. A cash index, a CFD and a futures contract can have different prices."], ["Compare the context", "Add another timeframe of the same instrument. Ready reports can be compared without another scan."], ["Return to the decision", "Save the original read. Come back with a later screenshot to inspect what changed and record your own lesson."]] },
  forex: { title: "A second look at your forex chart", headline: "Keep the pair. Keep the precision.", intro: "Review the structure around your forex setup with the original chart close at hand. Pocket Bullseye keeps the displayed price precision in its level scanner.", question: "Does the shorter timeframe agree with the wider picture?", steps: [["Show the full price scale", "Include the pair, timeframe and complete decimal labels. Cropping away the axis can make an exact level impossible to verify."], ["Use the same broker and pair", "Compare like-for-like charts. An unverified identity stays flagged instead of counting as agreement."], ["Record the lesson", "Tag the setup and write your own observation in the private notebook. Screenshots alone do not prove a fill or a profit."]] },
  review: { title: "Make your next chart review count", headline: "Your original idea. What actually changed.", intro: "Build a private record of your setups. Explore the original and later screenshots, review changes in the evidence, and keep the lessons you choose to use.", question: "Was the idea wrong—or did the chart change?", steps: [["Keep the original", "Successful scans are saved on your device. The original analysis stays attached to its screenshot."], ["Add the later chart", "Use the same instrument and timeframe. Step through the actual snapshots and the comparison's findings."], ["Make the lesson yours", "Search your history, add tags and pin personal rules. Export a private backup to protect your notebook."]] },
} as const;
type Key = keyof typeof guides;
function guide(key: string) { return Object.prototype.hasOwnProperty.call(guides, key) ? guides[key as Key] : null; }
export async function generateMetadata({ params }: { params: Promise<{ useCase: string }> }): Promise<Metadata> {
  const { useCase } = await params; const item = guide(useCase); if (!item) return {};
  const url = `https://pocket.nashaimarkets.com/pocket-bullseye/${useCase}`;
  return { title: { absolute: `${item.title} | Pocket Bullseye` }, description: item.intro, alternates: { canonical: url }, robots: { index: true, follow: true }, openGraph: { title: item.title, description: item.intro, url, type: "website", images: [] }, twitter: { card: "summary", title: item.title, description: item.intro, images: [] } };
}
export default async function PocketUseCase({ params }: { params: Promise<{ useCase: string }> }) {
  const { useCase } = await params; const item = guide(useCase); if (!item) notFound();
  return <div className={`${styles.page} ${styles.focusedPage}`}><IntroductionVisit/>
    <a className={styles.skip} href="#pocket-use-case">Skip to content</a>
    <header className={styles.header}><a href="/pocket-bullseye" className={styles.brand}><img src="/pocket-marketing/app-icon.png" width="48" height="48" alt=""/><span>Pocket Bullseye<small>Your chart. A second opinion.</small></span></a><SampleLink className={styles.textLink}/></header>
    <main id="pocket-use-case"><section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>{item.title}</p><h1>{item.headline}</h1><p className={styles.lead}>{item.intro}</p><p className={styles.supporting}>{item.question}</p><SampleLink className={styles.button}/><p className={styles.offer}>Fictional index example · no upload or account needed</p><p className={styles.sampleLink}><a href={`/pocket?utm_campaign=${useCase}`}>Open the web app with my own chart ↗</a></p></div><div className={styles.heroVisual}><img className={styles.emblem} src="/pocket-marketing/app-icon.png" width="384" height="384" alt="Pocket Bullseye app icon"/></div></section>
      <section className={styles.evidence}><div className={styles.sectionIntro}><h2>From a screenshot to a considered decision.</h2></div><div className={styles.evidenceGrid}>{item.steps.map(([title,copy],i) => <article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className={styles.lastCall} aria-label="Try Pocket Bullseye on iPhone"><div><p className={styles.eyebrow}>TRY YOUR OWN CHART</p><h2>One complete analysis free.</h2><p className={styles.offer}>Then £4.99/month in the UK if you subscribe. Regional pricing varies. Manage or cancel in Apple settings.</p></div><AppStoreLink className={styles.button}>Get the iPhone &amp; iPad app ↗</AppStoreLink></section>
      <section className={styles.questions}><h2>Know what the chart can tell you.</h2><details><summary>Is this a live market feed?</summary><p>No. The analysis uses uploaded screenshots. It does not monitor future price crossings or reconstruct candles between snapshots.</p></details><details><summary>What if the evidence is unclear?</summary><p>AI can misread charts. Check the instrument, timeframe, prices and any marked level on the source platform. Missing evidence stays unverified.</p></details><details><summary>Where is my notebook stored?</summary><p>On your device. Clearing browser storage can remove it. Exported backups contain screenshots and notes; keep those files private.</p></details><details><summary>Are all these features in the iPhone app?</summary><p>This page describes the latest web experience. iPhone updates are released separately through Apple review. Check the current App Store release notes for installed-app features and subscription terms.</p></details></section>
    </main><footer className={styles.footer}><nav>{Object.entries(guides).map(([key,value]) => <a key={key} href={`/pocket-bullseye/${key}`}>{value.title}</a>)}<a href="/privacy">Privacy</a></nav><p>Educational chart review. Make your own decisions.</p><UsageControl/></footer>
  </div>;
}
