import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms of use for NASH AI Markets.",
};

export default function Terms() {
  return <main className="legal"><header><Link href="/">← NASH AI MARKETS</Link></header><article>
    <span>LEGAL</span><h1>Terms of Use</h1><p className="updated">Last updated: 1 September 2026</p>
    <h2>Educational information only</h2><p>NASH AI Markets provides general educational commentary. Nothing on this site or in a briefing is personal financial advice, a recommendation, an offer, or a solicitation to buy or sell any financial instrument.</p>
    <h2>AI chart reviews</h2><p>A Second Opinion may misread a screenshot, omit context or produce an incorrect interpretation. It is designed to challenge a user-supplied plan, not validate a trade or provide an instruction. Do not rely on it as confirmation of market price, execution conditions, suitability or likely outcome.</p>
    <h2>Trading risk</h2><p>Futures and options can produce substantial and rapid losses, including losses greater than an initial investment. You are solely responsible for your decisions, position sizing and risk management. Past performance does not predict future results.</p>
    <h2>No guarantee</h2><p>Markets are uncertain. We do not guarantee the accuracy, completeness or timeliness of information, uninterrupted access, or any trading outcome. Illustrative levels and scenarios are not live signals unless clearly stated otherwise.</p>
    <h2>Web memberships and Stripe billing</h2><p>Memberships purchased on the website are billed through Stripe at the price and interval shown during checkout. Web subscription management and cancellation are available through the customer portal or support. Cancellation stops future renewal and access normally continues until the end of the paid period. Apple cannot manage or refund a web membership. Nothing in these terms limits a cancellation, refund or other consumer right that cannot lawfully be excluded.</p>
    <h2>Pocket Bullseye subscriptions on iOS</h2><p>The iOS app offers Pocket Bullseye Monthly as a one-month auto-renewable subscription. Apple shows the applicable local price before purchase, and payment is charged to the Apple Account used for the purchase. The subscription renews automatically for another month unless cancelled in Apple Account subscription settings before the renewal date. Access normally continues until the current paid period ends. Restore Purchases restores an eligible active entitlement. App Store refund requests are handled by Apple, are subject to Apple&apos;s rules and applicable law, and may be requested at <a href="https://reportaproblem.apple.com/" target="_blank" rel="noreferrer">reportaproblem.apple.com</a>. Pocket Bullseye cannot directly issue an App Store refund.</p>
    <h2>Separate purchase channels</h2><p>A Stripe web membership and an Apple in-app subscription are separate purchases managed by the provider used at checkout. A purchase, cancellation or restore on one channel does not automatically create, transfer, restore or cancel a subscription on the other unless Pocket Bullseye expressly states otherwise.</p>
    <h2>Web founding offers</h2><p>The Founding 650 web offer, when available, is governed by the offer shown before Stripe checkout. Its continuous-price guarantee applies only while the same Stripe subscription remains paid and uninterrupted. Cancellation, lapse or loss of paid status ends that guarantee; a later subscription uses the price then available. A web founding guarantee does not apply to an Apple subscription unless the App Store offer expressly says so.</p>
    <h2>Service availability</h2><p>Provider outages, delayed data, maintenance and other technical conditions may limit or suspend market output. Bullseye fails closed when current verified inputs are unavailable, and membership does not guarantee uninterrupted market-data availability.</p>
    <h2>Pocket Bullseye service</h2><p>Pocket Bullseye audits only the evidence visible in the images you submit. It can misread, omit or misunderstand chart content and does not verify your brokerage account, live market price, instrument specification or order details. Its score, grade and verdict are decision-support outputs, not trading signals. Reasonable request limits may apply to protect availability. Access may be changed or suspended for maintenance, security, misuse or provider outages.</p>
    <h2>Uploaded charts and saved decisions</h2><p>You must have the right to submit an image and must remove personal, confidential and account information before upload. Saved Pocket decisions are held in the browser or app&apos;s local device storage rather than synchronised to an account. You are responsible for retaining or deleting them and should not rely on local device storage as a permanent archive.</p>
    <h2>Acceptable use</h2><p>Content is for your personal use. You may not republish, resell, scrape or distribute briefings without written permission.</p>
    <h2>Statutory rights</h2><p>Nothing in these terms excludes rights or remedies that cannot lawfully be excluded, including applicable consumer cancellation and refund rights.</p>
    <h2>Contact</h2><p>Questions can be sent to <a href="mailto:hello@nashaimarkets.com">hello@nashaimarkets.com</a>.</p>
  </article></main>;
}
