create table if not exists public.launch_waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(trim(email)) and length(email) between 3 and 254),
  source text not null default 'launch-page' check (source in ('launch-page', 'homepage')),
  status text not null default 'pending' check (status in ('pending', 'invited', 'joined', 'declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists launch_waitlist_status_created_idx
  on public.launch_waitlist (status, created_at);

alter table public.launch_waitlist enable row level security;

comment on table public.launch_waitlist is
  'Server-managed launch waiting list. No client policies and no automatic membership grant.';

create table if not exists public.founding_member_onboarding (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null check (email = lower(trim(email)) and length(email) between 3 and 254),
  primary_goal text not null check (primary_goal in ('market-structure', 'risk-discipline', 'options-context')),
  experience_level text not null check (experience_level in ('developing', 'experienced', 'professional')),
  preferred_session text not null check (preferred_session in ('london', 'new-york', 'both')),
  risk_acknowledged boolean not null check (risk_acknowledged),
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'accepted', 'declined')),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists founding_member_onboarding_status_idx
  on public.founding_member_onboarding (status, submitted_at);

alter table public.founding_member_onboarding enable row level security;

comment on table public.founding_member_onboarding is
  'Server-managed Founding Member onboarding preferences. Submission never grants entitlement automatically.';
