create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  email text not null
    check (email = lower(trim(email)) and length(email) between 3 and 254),
  plan text not null default 'free'
    check (plan in ('free', 'pro', 'elite')),
  status text not null default 'inactive'
    check (length(trim(status)) between 2 and 64),
  stripe_customer_id text,
  stripe_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists memberships_email_key
  on public.memberships (email);

create unique index if not exists memberships_stripe_customer_key
  on public.memberships (stripe_customer_id)
  where stripe_customer_id is not null;

create unique index if not exists memberships_stripe_subscription_key
  on public.memberships (stripe_subscription_id)
  where stripe_subscription_id is not null;

create index if not exists memberships_access_idx
  on public.memberships (email, plan, status, current_period_end);

alter table public.memberships enable row level security;

revoke all on table public.memberships from anon, authenticated;
grant select on table public.memberships to authenticated;

drop policy if exists "members can read their own membership" on public.memberships;
create policy "members can read their own membership"
  on public.memberships
  for select
  to authenticated
  using (
    email = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
  );

comment on table public.memberships is
  'Server-managed Stripe membership entitlements. Authenticated members may read only the row matching their verified JWT email.';
