create table if not exists public.membership_previews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_tier text not null check (target_tier in ('pro', 'elite')),
  period_start timestamptz not null,
  claimed_at timestamptz not null default now(),
  unique (user_id, target_tier, period_start)
);

create index if not exists membership_previews_user_claimed_idx
  on public.membership_previews (user_id, claimed_at desc);

alter table public.membership_previews enable row level security;

comment on table public.membership_previews is
  'Server-managed, single-use Progressive Access preview claims. Service-role access only.';
