create table if not exists public.bullseye_verified_outcomes (
  id bigint generated by default as identity primary key,
  snapshot_as_of timestamptz not null,
  horizon text not null default 'daily_close' check (horizon in ('daily_close')),
  predicted_bias text not null check (predicted_bias in ('bullish', 'neutral', 'bearish')),
  actual_bias text not null check (actual_bias in ('bullish', 'neutral', 'bearish')),
  verification_source text not null check (length(trim(verification_source)) > 0),
  verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (snapshot_as_of, horizon)
);

create index if not exists bullseye_verified_outcomes_verified_idx
  on public.bullseye_verified_outcomes (verified_at desc);

alter table public.bullseye_verified_outcomes enable row level security;

comment on table public.bullseye_verified_outcomes is
  'Server-managed verified directional outcomes. No synthetic, modelled, or unverified rows.';
